name: flutter_starter_project
description: A Nero Lab Project created by Nero Lab CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  awesome_dialog: ^3.0.2
  cached_network_image: ^3.2.0
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.0.5
  dartz: ^0.10.1
  device_info_plus: ^10.1.2
  dio: ^5.7.0
  equatable: ^2.0.3
  firebase_analytics: ^11.3.1
  firebase_core: ^3.4.1
  firebase_messaging: ^15.1.1
  fluentui_system_icons: ^1.1.153
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_launcher_icons: ^0.12.0
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  flutter_sheet_localization: ^5.1.1
  form_field_validator: ^1.1.0
  get: ^4.6.1
  get_it: ^7.2.0
  google_fonts: ^4.0.4
  infinite_scroll_pagination: ^4.0.0
  json_annotation: ^4.4.0
  sentry_flutter: ^8.9.0
  shared_preferences: ^2.0.11
  youtube_player_flutter: ^9.0.3

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  device_preview: ^1.2.0
  flutter_driver:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_sheet_localization_generator: ^5.1.7
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.1.3
  mockito: ^5.0.17
  mocktail: ^1.0.4
  network_image_mock: ^2.0.1
  very_good_analysis: ^6.0.0

dependency_overrides:
  analyzer: ^2.6.0
  intl: ^0.19.0
  meta: ^1.7.0
  provider: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
