name: flutter_tdd_starter

on: [pull_request, push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1.5.3

      - name: Install Dependencies
        run: flutter packages get

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          min_coverage: 80
          exclude: '**/*.g.dart lib/**.g.dart lib/core/** lib/configs/** lib/utils/**'
